# ref. https://goreleaser.com/customization/build/
builds:
  - id: avalanche-network-runner
    main: ./main.go
    binary: avalanche-network-runner
    flags:
      - -v
    ldflags:
      - -X 'github.com/ava-labs/avalanche-network-runner/cmd.Version={{.Version}}'
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: ava-labs
    name: avalanche-network-runner
