// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	api "github.com/DioneProtocol/odyssey-network-runner/api"
	admin "github.com/DioneProtocol/odysseygo/api/admin"

	alpha "github.com/DioneProtocol/odysseygo/vms/alpha"

	evm "github.com/DioneProtocol/coreth/plugin/delta"

	health "github.com/DioneProtocol/odysseygo/api/health"

	indexer "github.com/DioneProtocol/odysseygo/indexer"

	info "github.com/DioneProtocol/odysseygo/api/info"

	ipcs "github.com/DioneProtocol/odysseygo/api/ipcs"

	keystore "github.com/DioneProtocol/odysseygo/api/keystore"

	mock "github.com/stretchr/testify/mock"

	omegavm "github.com/DioneProtocol/odysseygo/vms/omegavm"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AdminAPI provides a mock function with given fields:
func (_m *Client) AdminAPI() admin.Client {
	ret := _m.Called()

	var r0 admin.Client
	if rf, ok := ret.Get(0).(func() admin.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(admin.Client)
		}
	}

	return r0
}

// DChainAPI provides a mock function with given fields:
func (_m *Client) DChainAPI() evm.Client {
	ret := _m.Called()

	var r0 evm.Client
	if rf, ok := ret.Get(0).(func() evm.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(evm.Client)
		}
	}

	return r0
}

// DChainEthAPI provides a mock function with given fields:
func (_m *Client) DChainEthAPI() api.EthClient {
	ret := _m.Called()

	var r0 api.EthClient
	if rf, ok := ret.Get(0).(func() api.EthClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.EthClient)
		}
	}

	return r0
}

// DChainIndexAPI provides a mock function with given fields:
func (_m *Client) DChainIndexAPI() indexer.Client {
	ret := _m.Called()

	var r0 indexer.Client
	if rf, ok := ret.Get(0).(func() indexer.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(indexer.Client)
		}
	}

	return r0
}

// HealthAPI provides a mock function with given fields:
func (_m *Client) HealthAPI() health.Client {
	ret := _m.Called()

	var r0 health.Client
	if rf, ok := ret.Get(0).(func() health.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(health.Client)
		}
	}

	return r0
}

// InfoAPI provides a mock function with given fields:
func (_m *Client) InfoAPI() info.Client {
	ret := _m.Called()

	var r0 info.Client
	if rf, ok := ret.Get(0).(func() info.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(info.Client)
		}
	}

	return r0
}

// IpcsAPI provides a mock function with given fields:
func (_m *Client) IpcsAPI() ipcs.Client {
	ret := _m.Called()

	var r0 ipcs.Client
	if rf, ok := ret.Get(0).(func() ipcs.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ipcs.Client)
		}
	}

	return r0
}

// KeystoreAPI provides a mock function with given fields:
func (_m *Client) KeystoreAPI() keystore.Client {
	ret := _m.Called()

	var r0 keystore.Client
	if rf, ok := ret.Get(0).(func() keystore.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keystore.Client)
		}
	}

	return r0
}

// OChainAPI provides a mock function with given fields:
func (_m *Client) OChainAPI() omegavm.Client {
	ret := _m.Called()

	var r0 omegavm.Client
	if rf, ok := ret.Get(0).(func() omegavm.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(omegavm.Client)
		}
	}

	return r0
}

// OChainIndexAPI provides a mock function with given fields:
func (_m *Client) OChainIndexAPI() indexer.Client {
	ret := _m.Called()

	var r0 indexer.Client
	if rf, ok := ret.Get(0).(func() indexer.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(indexer.Client)
		}
	}

	return r0
}

// AChainAPI provides a mock function with given fields:
func (_m *Client) AChainAPI() alpha.Client {
	ret := _m.Called()

	var r0 alpha.Client
	if rf, ok := ret.Get(0).(func() alpha.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(alpha.Client)
		}
	}

	return r0
}

// AChainWalletAPI provides a mock function with given fields:
func (_m *Client) AChainWalletAPI() alpha.WalletClient {
	ret := _m.Called()

	var r0 alpha.WalletClient
	if rf, ok := ret.Get(0).(func() alpha.WalletClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(alpha.WalletClient)
		}
	}

	return r0
}
